-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
--then modified because it didnt work right away xD
 
CREATE TABLE IF NOT EXISTS public.users
(
    user_id serial NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
);
CREATE TABLE IF NOT EXISTS public.products
(
    product_id serial NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    price integer NOT NULL,
    category character varying COLLATE pg_catalog."default" NOT NULL,
    times_ordered integer,
    CONSTRAINT products_pkey PRIMARY KEY (product_id)
);


CREATE TABLE IF NOT EXISTS public.orders
(
    order_id serial NOT NULL  ,
    status character varying(100) COLLATE pg_catalog."default" NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.orders_products
(
    order_id integer NOT NULL,
    product_id integer NOT NULL
);



ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT user_id FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_user_id
    ON public.orders(user_id);


ALTER TABLE IF EXISTS public.orders_products
    ADD CONSTRAINT order_id FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders_products
    ADD CONSTRAINT product_id FOREIGN KEY (product_id)
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

 